// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ExtensibleAdventureWorks.Business.Entities
{

    // vJobCandidateEmployment
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public partial class HumanResources_VJobCandidateEmployment
    {
        public int JobCandidateId { get; set; } // JobCandidateID (Primary key)
        public System.DateTime? Emp46StartDate { get; set; } // Emp.StartDate
        public System.DateTime? Emp46EndDate { get; set; } // Emp.EndDate
        public string Emp46OrgName { get; set; } // Emp.OrgName (length: 100)
        public string Emp46JobTitle { get; set; } // Emp.JobTitle (length: 100)
        public string Emp46Responsibility { get; set; } // Emp.Responsibility
        public string Emp46FunctionCategory { get; set; } // Emp.FunctionCategory
        public string Emp46IndustryCategory { get; set; } // Emp.IndustryCategory
        public string Emp46Loc46CountryRegion { get; set; } // Emp.Loc.CountryRegion
        public string Emp46Loc46State { get; set; } // Emp.Loc.State
        public string Emp46Loc46City { get; set; } // Emp.Loc.City
    }

}
// </auto-generated>
