// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ExtensibleAdventureWorks.Business.Entities
{

    // Department
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public partial class HumanResources_Department
    {

        ///<summary>
        /// Primary key for Department records.
        ///</summary>
        public short DepartmentId { get; set; } // DepartmentID (Primary key)

        ///<summary>
        /// Name of the department.
        ///</summary>
        public string Name { get; set; } // Name (length: 50)

        ///<summary>
        /// Name of the group to which the department belongs.
        ///</summary>
        public string GroupName { get; set; } // GroupName (length: 50)

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        public System.DateTime ModifiedDate { get; set; } = System.DateTime.Now; // ModifiedDate

        // Reverse navigation

        /// <summary>
        /// Child HumanResources_EmployeeDepartmentHistories where [EmployeeDepartmentHistory].[DepartmentID] point to this entity (FK_EmployeeDepartmentHistory_Department_DepartmentID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<HumanResources_EmployeeDepartmentHistory> HumanResources_EmployeeDepartmentHistories { get; set; } = new System.Collections.Generic.List<HumanResources_EmployeeDepartmentHistory>(); // EmployeeDepartmentHistory.FK_EmployeeDepartmentHistory_Department_DepartmentID
    }

}
// </auto-generated>
