// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ExtensibleAdventureWorks.Business.Entities
{

    // ProductModelIllustration
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public partial class Production_ProductModelIllustrationConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Production_ProductModelIllustration>
    {
        public Production_ProductModelIllustrationConfiguration()
            : this("Production")
        {
        }

        public Production_ProductModelIllustrationConfiguration(string schema)
        {
            ToTable("ProductModelIllustration", schema);
            HasKey(x => new { x.ProductModelId, x.IllustrationId });

            Property(x => x.ProductModelId).HasColumnName(@"ProductModelID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.IllustrationId).HasColumnName(@"IllustrationID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            // Foreign keys
            HasRequired(a => a.Production_Illustration).WithMany(b => b.Production_ProductModelIllustrations).HasForeignKey(c => c.IllustrationId).WillCascadeOnDelete(false); // FK_ProductModelIllustration_Illustration_IllustrationID
            HasRequired(a => a.Production_ProductModel).WithMany(b => b.Production_ProductModelIllustrations).HasForeignKey(c => c.ProductModelId).WillCascadeOnDelete(false); // FK_ProductModelIllustration_ProductModel_ProductModelID
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
