// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ExtensibleAdventureWorks.Business.Entities
{

    // BillOfMaterials
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public partial class Production_BillOfMaterialConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Production_BillOfMaterial>
    {
        public Production_BillOfMaterialConfiguration()
            : this("Production")
        {
        }

        public Production_BillOfMaterialConfiguration(string schema)
        {
            ToTable("BillOfMaterials", schema);
            HasKey(x => x.BillOfMaterialsId);

            Property(x => x.BillOfMaterialsId).HasColumnName(@"BillOfMaterialsID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ProductAssemblyId).HasColumnName(@"ProductAssemblyID").HasColumnType("int").IsOptional();
            Property(x => x.ComponentId).HasColumnName(@"ComponentID").HasColumnType("int").IsRequired();
            Property(x => x.StartDate).HasColumnName(@"StartDate").HasColumnType("datetime").IsRequired();
            Property(x => x.EndDate).HasColumnName(@"EndDate").HasColumnType("datetime").IsOptional();
            Property(x => x.UnitMeasureCode).HasColumnName(@"UnitMeasureCode").HasColumnType("nchar").IsRequired().IsFixedLength().HasMaxLength(3);
            Property(x => x.BomLevel).HasColumnName(@"BOMLevel").HasColumnType("smallint").IsRequired();
            Property(x => x.PerAssemblyQty).HasColumnName(@"PerAssemblyQty").HasColumnType("decimal").IsRequired().HasPrecision(8,2);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            // Foreign keys
            HasOptional(a => a.ProductAssembly).WithMany(b => b.ProductAssembly).HasForeignKey(c => c.ProductAssemblyId).WillCascadeOnDelete(false); // FK_BillOfMaterials_Product_ProductAssemblyID
            HasRequired(a => a.Component).WithMany(b => b.Component).HasForeignKey(c => c.ComponentId).WillCascadeOnDelete(false); // FK_BillOfMaterials_Product_ComponentID
            HasRequired(a => a.Production_UnitMeasure).WithMany(b => b.Production_BillOfMaterials).HasForeignKey(c => c.UnitMeasureCode).WillCascadeOnDelete(false); // FK_BillOfMaterials_UnitMeasure_UnitMeasureCode
            this.ConfigureExtensions();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
