// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ExtensibleAdventureWorks.Business.Entities
{

    // vProductModelInstructions
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public partial class Production_VProductModelInstructionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Production_VProductModelInstruction>
    {
        public Production_VProductModelInstructionConfiguration()
            : this("Production")
        {
        }

        public Production_VProductModelInstructionConfiguration(string schema)
        {
            ToTable("vProductModelInstructions", schema);
            HasKey(x => new { x.ProductModelId, x.Name, x.Rowguid, x.ModifiedDate });

            Property(x => x.ProductModelId).HasColumnName(@"ProductModelID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(50).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Instructions).HasColumnName(@"Instructions").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.LocationId).HasColumnName(@"LocationID").HasColumnType("int").IsOptional();
            Property(x => x.SetupHours).HasColumnName(@"SetupHours").HasColumnType("decimal").IsOptional().HasPrecision(9,4);
            Property(x => x.MachineHours).HasColumnName(@"MachineHours").HasColumnType("decimal").IsOptional().HasPrecision(9,4);
            Property(x => x.LaborHours).HasColumnName(@"LaborHours").HasColumnType("decimal").IsOptional().HasPrecision(9,4);
            Property(x => x.LotSize).HasColumnName(@"LotSize").HasColumnType("int").IsOptional();
            Property(x => x.Step).HasColumnName(@"Step").HasColumnType("nvarchar").IsOptional().HasMaxLength(1024);
            Property(x => x.Rowguid).HasColumnName(@"rowguid").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            this.ConfigureExtensions();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
