// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ExtensibleAdventureWorks.Business.Entities
{

    // WorkOrderRouting
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public partial class Production_WorkOrderRoutingConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Production_WorkOrderRouting>
    {
        public Production_WorkOrderRoutingConfiguration()
            : this("Production")
        {
        }

        public Production_WorkOrderRoutingConfiguration(string schema)
        {
            ToTable("WorkOrderRouting", schema);
            HasKey(x => new { x.WorkOrderId, x.ProductId, x.OperationSequence });

            Property(x => x.WorkOrderId).HasColumnName(@"WorkOrderID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ProductId).HasColumnName(@"ProductID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.OperationSequence).HasColumnName(@"OperationSequence").HasColumnType("smallint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.LocationId).HasColumnName(@"LocationID").HasColumnType("smallint").IsRequired();
            Property(x => x.ScheduledStartDate).HasColumnName(@"ScheduledStartDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ScheduledEndDate).HasColumnName(@"ScheduledEndDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ActualStartDate).HasColumnName(@"ActualStartDate").HasColumnType("datetime").IsOptional();
            Property(x => x.ActualEndDate).HasColumnName(@"ActualEndDate").HasColumnType("datetime").IsOptional();
            Property(x => x.ActualResourceHrs).HasColumnName(@"ActualResourceHrs").HasColumnType("decimal").IsOptional().HasPrecision(9,4);
            Property(x => x.PlannedCost).HasColumnName(@"PlannedCost").HasColumnType("money").IsRequired().HasPrecision(19,4);
            Property(x => x.ActualCost).HasColumnName(@"ActualCost").HasColumnType("money").IsOptional().HasPrecision(19,4);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            // Foreign keys
            HasRequired(a => a.Production_Location).WithMany(b => b.Production_WorkOrderRoutings).HasForeignKey(c => c.LocationId).WillCascadeOnDelete(false); // FK_WorkOrderRouting_Location_LocationID
            HasRequired(a => a.Production_WorkOrder).WithMany(b => b.Production_WorkOrderRoutings).HasForeignKey(c => c.WorkOrderId).WillCascadeOnDelete(false); // FK_WorkOrderRouting_WorkOrder_WorkOrderID
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
