// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ExtensibleAdventureWorks.Business.Entities
{

    // UnitMeasure
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public partial class Production_UnitMeasure
    {

        ///<summary>
        /// Primary key.
        ///</summary>
        public string UnitMeasureCode { get; set; } // UnitMeasureCode (Primary key) (length: 3)

        ///<summary>
        /// Unit of measure description.
        ///</summary>
        public string Name { get; set; } // Name (length: 50)

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        public System.DateTime ModifiedDate { get; set; } = System.DateTime.Now; // ModifiedDate

        // Reverse navigation

        /// <summary>
        /// Child Production_BillOfMaterials where [BillOfMaterials].[UnitMeasureCode] point to this entity (FK_BillOfMaterials_UnitMeasure_UnitMeasureCode)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Production_BillOfMaterial> Production_BillOfMaterials { get; set; } = new System.Collections.Generic.List<Production_BillOfMaterial>(); // BillOfMaterials.FK_BillOfMaterials_UnitMeasure_UnitMeasureCode
        /// <summary>
        /// Child Production_Products where [Product].[SizeUnitMeasureCode] point to this entity (FK_Product_UnitMeasure_SizeUnitMeasureCode)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Production_Product> SizeUnitMeasureCode { get; set; } = new System.Collections.Generic.List<Production_Product>(); // Product.FK_Product_UnitMeasure_SizeUnitMeasureCode
        /// <summary>
        /// Child Production_Products where [Product].[WeightUnitMeasureCode] point to this entity (FK_Product_UnitMeasure_WeightUnitMeasureCode)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Production_Product> WeightUnitMeasureCode { get; set; } = new System.Collections.Generic.List<Production_Product>(); // Product.FK_Product_UnitMeasure_WeightUnitMeasureCode
        /// <summary>
        /// Child Purchasing_ProductVendors where [ProductVendor].[UnitMeasureCode] point to this entity (FK_ProductVendor_UnitMeasure_UnitMeasureCode)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Purchasing_ProductVendor> Purchasing_ProductVendors { get; set; } = new System.Collections.Generic.List<Purchasing_ProductVendor>(); // ProductVendor.FK_ProductVendor_UnitMeasure_UnitMeasureCode
    }

}
// </auto-generated>
