// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ExtensibleAdventureWorks.Business.Entities
{

    // Location
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public partial class Production_Location
    {

        ///<summary>
        /// Primary key for Location records.
        ///</summary>
        public short LocationId { get; set; } // LocationID (Primary key)

        ///<summary>
        /// Location description.
        ///</summary>
        public string Name { get; set; } // Name (length: 50)

        ///<summary>
        /// Standard hourly cost of the manufacturing location.
        ///</summary>
        public decimal CostRate { get; set; } = 0.00m; // CostRate

        ///<summary>
        /// Work capacity (in hours) of the manufacturing location.
        ///</summary>
        public decimal Availability { get; set; } = 0.00m; // Availability

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        public System.DateTime ModifiedDate { get; set; } = System.DateTime.Now; // ModifiedDate

        // Reverse navigation

        /// <summary>
        /// Child Production_ProductInventories where [ProductInventory].[LocationID] point to this entity (FK_ProductInventory_Location_LocationID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Production_ProductInventory> Production_ProductInventories { get; set; } = new System.Collections.Generic.List<Production_ProductInventory>(); // ProductInventory.FK_ProductInventory_Location_LocationID
        /// <summary>
        /// Child Production_WorkOrderRoutings where [WorkOrderRouting].[LocationID] point to this entity (FK_WorkOrderRouting_Location_LocationID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Production_WorkOrderRouting> Production_WorkOrderRoutings { get; set; } = new System.Collections.Generic.List<Production_WorkOrderRouting>(); // WorkOrderRouting.FK_WorkOrderRouting_Location_LocationID
    }

}
// </auto-generated>
