// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ExtensibleAdventureWorks.Business.Entities
{

    // vProductAndDescription
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public partial class Production_VProductAndDescription
    {
        public int ProductId { get; set; } // ProductID (Primary key)
        public string Name { get; set; } // Name (Primary key) (length: 50)
        public string ProductModel { get; set; } // ProductModel (Primary key) (length: 50)
        public string CultureId { get; set; } // CultureID (Primary key) (length: 6)
        public string Description { get; set; } // Description (Primary key) (length: 400)
    }

}
// </auto-generated>
