// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ExtensibleAdventureWorks.Business.Entities
{

    // Currency
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public partial class Sales_Currency
    {

        ///<summary>
        /// The ISO code for the Currency.
        ///</summary>
        public string CurrencyCode { get; set; } // CurrencyCode (Primary key) (length: 3)

        ///<summary>
        /// Currency name.
        ///</summary>
        public string Name { get; set; } // Name (length: 50)

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        public System.DateTime ModifiedDate { get; set; } = System.DateTime.Now; // ModifiedDate

        // Reverse navigation

        /// <summary>
        /// Child Sales_CountryRegionCurrencies where [CountryRegionCurrency].[CurrencyCode] point to this entity (FK_CountryRegionCurrency_Currency_CurrencyCode)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Sales_CountryRegionCurrency> Sales_CountryRegionCurrencies { get; set; } = new System.Collections.Generic.List<Sales_CountryRegionCurrency>(); // CountryRegionCurrency.FK_CountryRegionCurrency_Currency_CurrencyCode
        /// <summary>
        /// Child Sales_CurrencyRates where [CurrencyRate].[FromCurrencyCode] point to this entity (FK_CurrencyRate_Currency_FromCurrencyCode)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Sales_CurrencyRate> FromCurrencyCode { get; set; } = new System.Collections.Generic.List<Sales_CurrencyRate>(); // CurrencyRate.FK_CurrencyRate_Currency_FromCurrencyCode
        /// <summary>
        /// Child Sales_CurrencyRates where [CurrencyRate].[ToCurrencyCode] point to this entity (FK_CurrencyRate_Currency_ToCurrencyCode)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Sales_CurrencyRate> ToCurrencyCode { get; set; } = new System.Collections.Generic.List<Sales_CurrencyRate>(); // CurrencyRate.FK_CurrencyRate_Currency_ToCurrencyCode
    }

}
// </auto-generated>
