// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ExtensibleAdventureWorks.Business.Entities
{

    // vSalesPersonSalesByFiscalYears
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public partial class Sales_VSalesPersonSalesByFiscalYearConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Sales_VSalesPersonSalesByFiscalYear>
    {
        public Sales_VSalesPersonSalesByFiscalYearConfiguration()
            : this("Sales")
        {
        }

        public Sales_VSalesPersonSalesByFiscalYearConfiguration(string schema)
        {
            ToTable("vSalesPersonSalesByFiscalYears", schema);
            HasKey(x => new { x.JobTitle, x.SalesTerritory });

            Property(x => x.SalesPersonId).HasColumnName(@"SalesPersonID").HasColumnType("int").IsOptional();
            Property(x => x.FullName).HasColumnName(@"FullName").HasColumnType("nvarchar").IsOptional().HasMaxLength(152);
            Property(x => x.JobTitle).HasColumnName(@"JobTitle").HasColumnType("nvarchar").IsRequired().HasMaxLength(50).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.SalesTerritory).HasColumnName(@"SalesTerritory").HasColumnType("nvarchar").IsRequired().HasMaxLength(50).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.C2002).HasColumnName(@"2002").HasColumnType("money").IsOptional().HasPrecision(19,4);
            Property(x => x.C2003).HasColumnName(@"2003").HasColumnType("money").IsOptional().HasPrecision(19,4);
            Property(x => x.C2004).HasColumnName(@"2004").HasColumnType("money").IsOptional().HasPrecision(19,4);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
