// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ExtensibleAdventureWorks.Business.Entities
{

    // TaxAuditor
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public partial class custom_TaxAuditor
    {
        public int TaxAuditorId { get; set; } // TaxAuditorID (Primary key)
        public string FirstName { get; set; } // FirstName (length: 200)
        public string LastName { get; set; } // LastName (length: 200)

        // Reverse navigation

        /// <summary>
        /// Child Sales_Stores where [Store].[TaxAuditorID] point to this entity (FK_Store_TaxAuditor_TaxAuditorID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Sales_Store> Sales_Stores { get; set; } = new System.Collections.Generic.List<Sales_Store>(); // Store.FK_Store_TaxAuditor_TaxAuditorID
    }

}
// </auto-generated>
