// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ExtensibleAdventureWorks.Business.Entities
{

    // Store
    public partial class Sales_Store
    {
        public int? TaxAuditorId { get; set; } // TaxAuditorID

        // Foreign keys

        /// <summary>
        /// Parent custom_TaxAuditor pointed by [Store].([TaxAuditorId]) (FK_Store_TaxAuditor_TaxAuditorID)
        /// </summary>
        public virtual custom_TaxAuditor custom_TaxAuditor { get; set; } // FK_Store_TaxAuditor_TaxAuditorID
        /// <summary>
    }
}
