// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ExtensibleAdventureWorks.Business.Entities
{

    // OpeningHour
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public partial class custom_OpeningHour
    {
        public int BusinessEntityId { get; set; } // BusinessEntityID (Primary key)
        public int DayOfWeek { get; set; } // DayOfWeek (Primary key)
        public System.TimeSpan OpeningTime { get; set; } // OpeningTime
        public System.TimeSpan ClosingTime { get; set; } // ClosingTime

        // Foreign keys

        /// <summary>
        /// Parent Sales_Store pointed by [OpeningHour].([BusinessEntityId]) (FK_OpeningHour_Store_BusinessEntityID)
        /// </summary>
        public virtual Sales_Store Sales_Store { get; set; } // FK_OpeningHour_Store_BusinessEntityID
    }

}
// </auto-generated>
