// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ExtensibleAdventureWorks.Business.Entities
{

    // OpeningHour
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public partial class custom_OpeningHourConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<custom_OpeningHour>
    {
        public custom_OpeningHourConfiguration()
            : this("custom")
        {
        }

        public custom_OpeningHourConfiguration(string schema)
        {
            ToTable("OpeningHour", schema);
            HasKey(x => new { x.BusinessEntityId, x.DayOfWeek });

            Property(x => x.BusinessEntityId).HasColumnName(@"BusinessEntityID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.DayOfWeek).HasColumnName(@"DayOfWeek").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.OpeningTime).HasColumnName(@"OpeningTime").HasColumnType("time").IsRequired();
            Property(x => x.ClosingTime).HasColumnName(@"ClosingTime").HasColumnType("time").IsRequired();

            // Foreign keys
            HasRequired(a => a.Sales_Store).WithMany(b => b.custom_OpeningHours).HasForeignKey(c => c.BusinessEntityId).WillCascadeOnDelete(false); // FK_OpeningHour_Store_BusinessEntityID
            this.ConfigureExtensions();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
