// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ExtensibleAdventureWorks.Business.Entities
{
    // Store
    public partial class Sales_Store
    {

        // Reverse navigation

        /// <summary>
        /// Child custom_OpeningHours where [OpeningHour].[BusinessEntityID] point to this entity (FK_OpeningHour_Store_BusinessEntityID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<custom_OpeningHour> custom_OpeningHours { get; set; } = new System.Collections.Generic.List<custom_OpeningHour>(); // OpeningHour.FK_OpeningHour_Store_BusinessEntityID
    }
}
